#!/usr/bin/env bash

file=$1
w=$2
h=$3
x=$4
y=$5

filetype="$( file -Lb --mime-type "${file}")"

if [[ "${filetype}" =~ ^image ]]; then
  kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "${file}"
  exit 1
fi

if [[ "${filetype}" =~ ^video ]]; then
  # vidthumb is from here:
  # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
  kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(vidthumb "${file}")"
  exit 1
fi

if [[ "${filetype}" =~ ^text ]] || [[ "${filetype}" =~ json$ ]]; then
  bat "${file}" --color=always
  exit 1
fi

if [[ "${filetype}" =~ pdf$ ]]; then
  pdftotext "${file}" - | less
  exit 1
fi

case "${file}" in
# 	*.tgz|*.tar.gz) tar tzf "$1";;
# 	*.tar.bz2|*.tbz2) tar tjf "$1";;
# 	*.tar.txz|*.txz) xz --list "$1";;
# 	*.tar) tar tf "$1";;
 	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1";;
# 	*.rar) unrar l "$1";;
# 	*.7z) 7z l "$1";;
# 	*.[1-8]) man "$1" | col -b ;;
# 	*.o) nm "$1" | less ;;
# 	*.iso) iso-info --no-header -l "$1";;
# 	*.docx) docx2txt "$1" - ;;
# 	*.csv) cat "$1" | sed s/,/\\n/g ;;
# 	*.pdf)
# 		CACHE=$(mktemp /tmp/thumbcache.XXXXX)
# 		pdftoppm -png -f 1 -singlefile "$1" "$CACHE"
# 		$HOME/.config/lf/image draw "$CACHE.png" $num 1 $numb $numc
# 		;;
# 	*.epub)
# 		CACHE=$(mktemp /tmp/thumbcache.XXXXX)
# 		epub-thumbnailer "$1" "$CACHE" 1024
# 		$HOME/.config/lf/image draw "$CACHE" $num 1 $numb $numc
# 		;;
# 	*) highlight --out-format ansi "$1" || cat "$1";;
esac

pistol "${file}"
