#!/usr/bin/env bash

# Standard Unix tools
alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -la --color=auto'

alias grep='grep --color=auto'
alias cl='clear'
alias tree='tree -C'

# Bat
if which bat >/dev/null 2>&1; then
	alias cat='bat'
fi

# Chezmoi
if which chezmoi >/dev/null 2>&1; then
	alias dotfiles='chezmoi'
  alias cm='chezmoi'
fi

# Neovim
if which nvim >/dev/null 2>&1; then
	alias v='nvim'
fi
